carbon_inventory/authentication/routes.py
from re import template
from flask import Blueprint, render_template, request, redirect, url_for, flash
from carbon_inventory.models import User, db, check_password_hash
from carbon_inventory.forms import UserLoginForm

# Imports for Flask Login
from flask_login import login_user, logout_user, current_user, login_required 

auth = Blueprint('auth', __name__, template_folder = 'auth_templates')

@auth.route('/signup', methods = ['GET', 'POST'])
def signup():
    form = UserLoginForm()

    try:
        if request.method == 'POST' and form.validate_on_submit():
            first_name = form.first_name.data
            last_name = form.last_name.data
            email = form.email.data
            password = form.password.data
            print(email, password)

            user = User(first_name, last_name, email, password = password)

            db.session.add(user)
            db.session.commit()

            flash(f"You have successfully created a user account: {email}", 'user-created')

            return redirect(url_for('site.home'))

    except:
        raise Exception('Invalid Form Data: Please Check Your Form')

    return render_template('signup.html', form=form)


@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    form = UserLoginForm()

    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            password = form.password.data 
            print(email, password)

            logged_user = User.query.filter(User.email == email).first() 
            if logged_user and check_password_hash(logged_user.password, password):
                login_user(logged_user)
                flash('You were successfully logged in: Via email/password', 'auth-success')
                return redirect(url_for('site.profile'))
            else:
                flash('Your email/password is incorrect', 'auth-failed')
                return redirect(url_for('auth.signin'))
    except:
        raise Exception('Invalid Form Data: Please Check Your Form')
    return render_template('signin.html', form=form)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('site.home'))

carbon_inventory/site/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash #added request, redirect, url_for, & flash
from flask_login.utils import login_required

from carbon_inventory.models import User, db, Carbon #added db & User
from flask_login import current_user
# from carbon_inventory.forms import CarbonForm # added UserArtistForm

"""
Note that in code below,
Some arguments are specified when creating Blueprint object
First argument, "site", is Blueprint's name which is used by flask routing mechanism
Second argument, __name__, is Blueprint's import name which flask using to locate Blueprint's resources
"""


site = Blueprint('site', __name__, template_folder='site_templates')

@site.route('/')
def home():
    return render_template('index.html')

@site.route('/profile')
@login_required
def profile():
    carbons = Carbon.query.filter_by(user_token = current_user.token).all()
    return render_template('profile.html', carbons=carbons)

carbon_inventory/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="../static/css/main.css">
<title>Alex's API</title>
</head>
<body>

<body>

      <!-- Nav Bar Start -->
      <nav class="home">
        <h1>Alto Energy</h1>
        <ul class="home_links">
            <li><a href="{{ url_for('site.home') }}">Home</a></li>
            <li><a href="{{ url_for('site.profile') }}">Profile</a></li>
            {% if current_user.is_authenticated %}
            <li><a href="{{ url_for('auth.logout') }}">Log Out</a></li>
            {% else %}
            <li><a href="{{ url_for('auth.signin') }}">Sign In</a></li>
            <li><a href="{{ url_for('auth.signup') }}">Sign Up Free!</a></li>
            {% endif %}
         </ul>    
    </nav>

    <!-- Nav Bar End -->

    {% block content %}
    {% endblock content %}


<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
    
</body>
</html>

carbon_inventory/templates/forms.html
<!--  HTML produced by the Flask Form -->


<form method = "POST">
    {{form.hidden_tag()}}
    <div class="form-group">
        <fieldset id="first-name-field">
            {{ form.first_name.label }}
            {{ form.first_name(class = "form-control", placeholder = "Place First Name Here")}}
        </fieldset>
        <fieldset id="last-name-field">
            {{ form.last_name.label }}
            {{ form.last_name(class = "form-control", placeholder = "Place Last Name Here")}}
        </fieldset>
        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class = "form-control", placeholder = "Place Email Here")}}
        </fieldset>
        <fieldset id="pass-field">
            {{ form.password.label }}
            {{ form.password(class = "form-control", placeholder = "Place Password Here")}}
        </fieldset>

        <!-- Submit Button Here -->
        {{ form.submit_button(class = "btn btn-secondary btn-block") }}
    </div>

</form>